---
".gitlab-ci.yml":
  delete: true
appveyor.yml:
  delete: true

Gemfile:
  optional:
    ":development":
    - gem: github_changelog_generator
Rakefile:
  changelog_user: puppetlabs
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
.github/workflows/nightly.yml:
  unmanaged: false
.github/workflows/pr_test.yml:
  unmanaged: false
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
.github/workflows/auto_release.yml:
  unmanaged: false
.github/workflows/spec.yml:
  checks: 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
  unmanaged: false
.github/workflows/release.yml:
  unmanaged: false
.travis.yml:
  delete: true
